import { ItemRegistry } from "./definitions/item-registry";
import type { AmmoDefinition } from "./definitions/item-definition";

/** Shared game catalog for all static item definitions. */
export const itemRegistry = new ItemRegistry();

itemRegistry.register({
	id: "desert_eagle",
	name: "Desert Eagle",
	description: "A powerful handgun.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "magnum",
	ammoType: "magnum",
	magazineSize: 7,
	baseDamage: 30,
	fireRate: 0.4,
	range: 25,
	projectileCount: 1,
	spreadDegrees: 0,
	projectileSpeed: 25,
	reloadTime: 1.1,
});

itemRegistry.register({
	id: "m4",
	name: "M4",
	description: "A reliable modern assault rifle.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "rifle",
	ammoType: "rifle",
	magazineSize: 30,
	baseDamage: 20,
	fireRate: 0.1,
	range: 35,
	projectileCount: 1,
	spreadDegrees: 2,
	projectileSpeed: 32,
	reloadTime: 1.8,
});

itemRegistry.register({
	id: "shotgun",
	name: "Shotgun",
	description: "A close-range shotgun with a wide spread.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "shotgun",
	ammoType: "shotgun_shell",
	magazineSize: 8,
	baseDamage: 12,
	fireRate: 0.8,
	range: 15,
	projectileCount: 6,
	spreadDegrees: 18,
	projectileSpeed: 24,
	reloadTime: 2.2,
});

const ammoDefinitions: readonly AmmoDefinition[] = [
	{
		id: "handgun",
		name: "Handgun Ammo",
		description: "Standard handgun ammunition.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "handgun",
	},
	{
		id: "shotgun_shell",
		name: "Shotgun Shells",
		description: "Shells for shotguns.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "shotgun_shell",
	},
	{
		id: "smg",
		name: "SMG Ammo",
		description: "Ammunition for submachine guns.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "smg",
	},
	{
		id: "rifle",
		name: "Rifle Ammo",
		description: "Ammunition for assault rifles.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "rifle",
	},
	{
		id: "sniper",
		name: "Sniper Ammo",
		description: "High-caliber sniper ammunition.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "sniper",
	},
	{
		id: "magnum",
		name: "Magnum Ammo",
		description: "Powerful magnum ammunition.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "magnum",
	},
	{
		id: "rocket",
		name: "Rockets",
		description: "Explosive rocket launcher ammunition.",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "rocket",
	},
];

itemRegistry.registerMany(ammoDefinitions);

itemRegistry.register({
	id: "first_aid",
	name: "First Aid",
	description: "Restores health.",
	type: "consumable",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: false,
	quickAssignable: true,
	effectId: "restore_health",
});
