import { ItemRegistry } from "./definitions/item-registry";
import type { AmmoDefinition, ProjectileDefinition } from "./definitions/item-definition";
import { getWeaponVisualDefinition } from "./definitions/get-weapon-definition";

/** Shared game catalog for all static item definitions. */
export const itemRegistry = new ItemRegistry();

const createProjectileDefinition = (image: string): ProjectileDefinition => ({
	image,
	visual: {
		size: { x: 0.2, y: 0.1 },
		scale: { x: 1, y: 1 },
		anchor: { x: 0, y: 0 },
		pivot: { x: 0.5, y: 0.5 },
	},
	collider: {
		offset: { x: 0, y: 0 },
		size: { x: 0.2, y: 0.2 },
	},
});



itemRegistry.register({
	id: "desert_eagle",
	weaponId: "desert-eagle",
	name: "Desert Eagle",
	description: "A powerful handgun.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "magnum",
	ammoType: "heavy",
	magazineSize: 7,
	baseDamage: 30,
	fireRate: 0.4,
	range: 25,
	projectileCount: 1,
	spreadDegrees: 0,
	projectileSpeed: 25,
	reloadTime: 1.1,
	weaponVisual: getWeaponVisualDefinition("desert-eagle"),
	projectile: createProjectileDefinition("bullet:heavy"),
});

itemRegistry.register({
	id: "m4",
	weaponId: "m4",
	name: "M4",
	description: "A reliable modern assault rifle.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "rifle",
	ammoType: "medium",
	magazineSize: 30,
	baseDamage: 20,
	fireRate: 0.1,
	range: 35,
	projectileCount: 1,
	spreadDegrees: 2,
	projectileSpeed: 32,
	reloadTime: 1.8,
	weaponVisual:getWeaponVisualDefinition("m4"),
	projectile: createProjectileDefinition("bullet:medium"),
});

itemRegistry.register({
	id: "shotgun",
	weaponId: "shotgun",
	name: "Shotgun",
	description: "A close-range shotgun with a wide spread.",
	type: "weapon",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: true,
	quickAssignable: true,
	weaponType: "shotgun",
	ammoType: "shells",
	magazineSize: 8,
	baseDamage: 12,
	fireRate: 0.8,
	range: 15,
	projectileCount: 6,
	spreadDegrees: 18,
	projectileSpeed: 24,
	reloadTime: 2.2,
	weaponVisual:getWeaponVisualDefinition("shotgun"),
	projectile: createProjectileDefinition("bullet:shells"),
});

const ammoDefinitions: readonly AmmoDefinition[] = [
	{
		id: "light_ammo",
		name: "Light Ammo",
		description: "Light ammunition for handguns and submachine guns.",
		icon: "ammo-light",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "light",
	},
	{
		id: "shells_ammo",
		name: "Shells",
		description: "Shotgun shells and other smoothbore ammunition.",
		icon: "ammo-shells",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "shells",
	},
	{
		id: "medium_ammo",
		name: "Medium Ammo",
		description: "Medium ammunition for assault rifles and similar weapons.",
		icon: "ammo-medium",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "medium",
	},
	{
		id: "heavy_ammo",
		name: "Heavy Ammo",
		description: "Heavy ammunition for magnums and sniper rifles.",
		icon: "ammo-heavy",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "heavy",
	},
	{
		id: "explosive_ammo",
		name: "Explosive Ammo",
		description: "Explosive ammunition for rocket and grenade launchers.",
		icon: "ammo-explosive",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoType: "explosive",
	},
];

itemRegistry.registerMany(ammoDefinitions);

itemRegistry.register({
	id: "first_aid",
	name: "First Aid",
	description: "Restores health.",
	type: "consumable",
	stackable: false,
	maxStack: 1,
	droppable: true,
	sellable: true,
	equippable: false,
	quickAssignable: true,
	effectId: "restore_health",
});
