import { GameObject } from "engine/common/entities/game-object";
import Vector2 from "engine/math/vector2";
import { Collider } from "engine/physics/components/collider";
import { PlayerMovement } from "../script-components/player/player-movement";
import { PlayerController } from "../script-components/player/player-controller";
import { PlayerCameraController } from "../script-components/player/player-camera-controller";
import { HealthComponent } from "../script-components/shared/health-component";
import { FallDamage } from "../script-components/player/fall-damage";
import { PlayerHud } from "../hud/hud";
import { ShieldComponent } from "../script-components/shared/shield-component";
import { WeaponHolder } from "../script-components/weapon/weapon";
import { DynamicBody } from "engine/physics/components/dynamic-body";
import { PlayerSpriteController } from "../script-components/player/sprite-controller";
import { QuickSlotInputController } from "../script-components/player/quick-slot-input-controller";
import { PlayerLifeController } from "../script-components/player/player-life-controller";
import { AimingController } from "../script-components/player/aiming-controller";
import { PlayerAimingArm } from "../script-components/player/player-aiming-arm";
import { PlayerSkin } from "../config/constants";
import { PlayerSkinComponent } from "../script-components/player/player-skin-component";
import { itemRegistry } from "../items/item-catalog";
import { InventoryComponent } from "../items/components/inventory-component";
import { QuickSlotsComponent } from "../items/components/quick-slots-component";
import { EquipmentComponent } from "../items/components/equipment-component";

type Params = {
	position: Vector2;
	skin?: PlayerSkin;
};
export const createPlayer = (params: Params): GameObject => {
	const { position, skin = PlayerSkin.SKIN1 } = params;
	const entity = new GameObject({
		position: position,
		rotation: 0,
		size: new Vector2(0.8, 1.8),
	});
	entity.addTag("player");
	entity.addComponent(new PlayerSkinComponent(skin));
	entity.addComponent(new PlayerSpriteController());
	entity.addComponent(new DynamicBody());
	entity.addComponent(new Collider(new Vector2(0, 0), new Vector2(0.5, 1)));
	entity.addComponent(new PlayerMovement());
	entity.addComponent(new PlayerController());
	entity.addComponent(new PlayerCameraController());
	entity.addComponent(new HealthComponent(100, 100, false));
	entity.addComponent(new ShieldComponent());
	entity.addComponent(new FallDamage());
	entity.addComponent(new PlayerHud());
	entity.addComponent(new PlayerLifeController());
	entity.addComponent(new PlayerAimingArm(skin));
	entity.addComponent(new QuickSlotInputController());
	entity.addComponent(new AimingController());
	const inventoryComponent = new InventoryComponent(itemRegistry);
	const desertEagle = inventoryComponent.inventory.createInstance(itemRegistry.get("desert_eagle"));
	const inventoryEntry = inventoryComponent.inventory.addInstance(desertEagle);
	const m4 = inventoryComponent.inventory.createInstance(itemRegistry.get("m4"));
	const m4Entry = inventoryComponent.inventory.addInstance(m4);
	const shotgun = inventoryComponent.inventory.createInstance(itemRegistry.get("shotgun"));
	const shotgunEntry = inventoryComponent.inventory.addInstance(shotgun);
	inventoryComponent.inventory.add("heavy_ammo", 42);
	inventoryComponent.inventory.add("medium_ammo", 90);
	inventoryComponent.inventory.add("shells_ammo", 24);
	const firstAid = inventoryComponent.inventory.createInstance(itemRegistry.get("first_aid"));
	const firstAidEntry = inventoryComponent.inventory.addInstance(firstAid);
	const quickSlots = new QuickSlotsComponent();
	quickSlots.set(0, null);
	quickSlots.set(1, inventoryEntry.entryId);
	quickSlots.set(2, m4Entry.entryId);
	quickSlots.set(3, shotgunEntry.entryId);
	quickSlots.set(4, firstAidEntry.entryId);
	entity.addComponent(inventoryComponent);
	entity.addComponent(quickSlots);
	const equipment = new EquipmentComponent();
	entity.addComponent(equipment);

	entity.addComponent(new WeaponHolder());
	const collider = entity.getComponent(Collider);
	const playerBody = entity.getComponent(DynamicBody);
	const playerMovement = entity.getComponent(PlayerMovement);
	playerMovement.direction.x = 1;
	collider.setSize(new Vector2(0.5, entity.transform.size.y));
	collider.setOffsetPosition(new Vector2(0, 0));
	playerBody.gravity = 60;
	playerBody.mass = 80;
	playerBody.friction = 1800;
	playerBody.dragScale = 109;
	playerMovement.forceX = 14000;
	playerMovement.forceY = 16000;
	playerMovement.maxJumpHeight = 1.2;
	playerMovement.dashForceX = 17000;
	playerMovement.dashMaxSpeedX = 13;
	playerMovement.dashDuration = 0.16;
	playerMovement.dashCooldown = 0.45;
	playerBody.bounciness = new Vector2(0, 0);
	return entity;
};
