import type { AmmoDefinition } from "../definitions/item-definition";

export const AMMO_DEFINITIONS: readonly AmmoDefinition[] = [
	{
		id: "light_ammo",
		name: "Light Ammo",
		description: "Light ammunition for handguns and submachine guns.",
		icon: "ammo-light",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoFamily: "light",
		projectileId: "bullet-light",
	},
	{
		id: "shells_ammo",
		name: "Shells",
		description: "Shotgun shells and other smoothbore ammunition.",
		icon: "ammo-shells",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoFamily: "shells",
		projectileId: "shell",
	},
	{
		id: "medium_ammo",
		name: "Medium Ammo",
		description: "Medium ammunition for assault rifles and similar weapons.",
		icon: "ammo-medium",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoFamily: "medium",
		projectileId: "bullet-medium",
	},
	{
		id: "heavy_ammo",
		name: "Heavy Ammo",
		description: "Heavy ammunition for magnums and sniper rifles.",
		icon: "ammo-heavy",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoFamily: "heavy",
		projectileId: "bullet-heavy",
	},
	{
		id: "explosive_ammo",
		name: "Explosive Ammo",
		description: "Explosive ammunition for rocket and grenade launchers.",
		icon: "ammo-explosive",
		type: "ammo",
		stackable: true,
		maxStack: 999,
		droppable: true,
		sellable: true,
		equippable: false,
		quickAssignable: false,
		ammoFamily: "explosive",
		projectileId: "rocket",
	},
];
