import type { WeaponDefinition } from "../definitions/item-definition";

export const WEAPON_DEFINITIONS: readonly WeaponDefinition[] = [
	{
		id: "desert_eagle",
		weaponId: "desert-eagle",
		name: "Desert Eagle",
		description: "A powerful handgun.",
		type: "weapon",
		icon: "spritesheet:weapons:desert-eagle",
		stackable: false,
		maxStack: 1,
		droppable: true,
		sellable: true,
		equippable: true,
		quickAssignable: true,
		weaponType: "magnum",
		ammoId: "heavy_ammo",
		magazineSize: 7,
		baseDamage: 30,
		fireRate: 0.4,
		range: 25,
		projectileCount: 1,
		spreadDegrees: 0,
		projectileSpeed: 25,
		reloadTime: 1.1,
		weaponVisual: {
			image: "spritesheet:weapons:desert-eagle",
			size: { x: 0.35, y: 0.35 },
			scale: { x: 1, y: 1 },
			anchor: { x: 0, y: 0 },
			pivot: { x: 0.5, y: 0.2 },
			handOffset: { x: 0.35, y: 0.35 },
			rotationOffsetDegrees: 45,
			projectileSpawnPoint: { x: 0.5, y: 0.2 },
		},
	},
	{
		id: "m4",
		weaponId: "m4",
		name: "M4",
		description: "A reliable modern assault rifle.",
		type: "weapon",
		icon: "spritesheet:weapons:m4",
		stackable: false,
		maxStack: 1,
		droppable: true,
		sellable: true,
		equippable: true,
		quickAssignable: true,
		weaponType: "rifle",
		ammoId: "medium_ammo",
		magazineSize: 30,
		baseDamage: 20,
		fireRate: 0.1,
		range: 35,
		projectileCount: 1,
		spreadDegrees: 2,
		projectileSpeed: 32,
		reloadTime: 1.8,
		weaponVisual: {
			image: "spritesheet:weapons:m4",
			size: { x: 0.7, y: 0.4 },
			scale: { x: 1, y: 1 },
			anchor: { x: 0, y: 0 },
			pivot: { x: 0.5, y: 0.4 },
			handOffset: { x: 0.3, y: 0.4 },
			rotationOffsetDegrees: 45,
			projectileSpawnPoint: { x: 0.5, y: 0.3 },
		},
	},
	{
		id: "shotgun",
		weaponId: "shotgun",
		name: "Shotgun",
		description: "A close-range shotgun with a wide spread.",
		type: "weapon",
		icon: "spritesheet:weapons:shotgun",
		stackable: false,
		maxStack: 1,
		droppable: true,
		sellable: true,
		equippable: true,
		quickAssignable: true,
		weaponType: "shotgun",
		ammoId: "shells_ammo",
		magazineSize: 8,
		baseDamage: 12,
		fireRate: 1,
		range: 15,
		projectileCount: 6,
		spreadDegrees: 18,
		projectileSpeed: 24,
		reloadTime: 2.2,
		weaponVisual: {
			image: "spritesheet:weapons:shotgun",
			size: { x: 0.7, y: 0.4 },
			scale: { x: 1, y: 1 },
			anchor: { x: 0, y: 0 },
			pivot: { x: 0.5, y: 0.4 },
			handOffset: { x: 0.3, y: 0.4 },
			rotationOffsetDegrees: 45,
			projectileSpawnPoint: { x: 0.5, y: 0.3 },
		},
	},
	{
		id: "rocket_launcher",
		weaponId: "rocket_launcher",
		name: "Rocket Launcher",
		description: "A powerful rocket launcher.",
		type: "weapon",
		icon: "spritesheet:weapons:rocket-launcher",
		stackable: false,
		maxStack: 1,
		droppable: true,
		sellable: true,
		equippable: true,
		quickAssignable: true,
		weaponType: "rocket_launcher",
		ammoId: "explosive_ammo",
		magazineSize: 3,
		baseDamage: 100,
		fireRate: 1,
		range: 15,
		projectileCount: 1,
		spreadDegrees: 0,
		projectileSpeed: 24,
		reloadTime: 3,
		weaponVisual: {
			image: "spritesheet:weapons:rocket-launcher",
			size: { x: 0.7, y: 0.4 },
			scale: { x: 1, y: 1 },
			anchor: { x: 0, y: 0 },
			pivot: { x: 0.5, y: 0.4 },
			handOffset: { x: 0.3, y: 0.4 },
			rotationOffsetDegrees: 45,
			projectileSpawnPoint: { x: 0.5, y: 0.3 },
		},
	},
];
