import { type AssetToPreload, GameAssetsTypes } from "engine/common/index";


export const PRELOAD_IMAGES_PATHS: AssetToPreload[] = [
	{
		type: GameAssetsTypes.Image,
		paths: [
			"/assets/textures/Analgesic.png",
			"/assets/textures/Boss.png",
			"/assets/textures/Box.png",
			"/assets/textures/Car1.png",
			"/assets/textures/Car2.png",
			"/assets/textures/Car3.png",
			"/assets/textures/Car4.png",
			"/assets/textures/Cloud.png",
			"/assets/textures/Crosshair1.png",
			"/assets/textures/Floor.png",
			"/assets/textures/Hand.png",
			"/assets/textures/House1.png",
			"/assets/textures/House2.png",
			"/assets/textures/House3.png",
			"/assets/textures/House4.png",
			"/assets/textures/Marker.png",
			"/assets/textures/Megaphone.png",
			"/assets/textures/NoVirus.png",
			"/assets/textures/None.png",
			"/assets/textures/PlayerJumpLeft.png",
			"/assets/textures/PlayerJumpRight.png",
			"/assets/textures/PlayerLeft.png",
			"/assets/textures/PlayerRight.png",
			"/assets/textures/Shield.png",
			"/assets/textures/SickManLeft.png",
			"/assets/textures/SickManRight.png",
			"/assets/textures/SneezeGuy.png",
			"/assets/textures/Soldier.png",
			"/assets/textures/SoldierWeapon.png",
			"/assets/textures/Spray.png",
			"/assets/textures/SprayLeft.png",
			"/assets/textures/SprayRight.png",
			"/assets/textures/Store1.png",
			"/assets/textures/Store2.png",
			"/assets/textures/Store3.png",
			"/assets/textures/Store4.png",
			"/assets/textures/Tape.png",
			"/assets/textures/Tree.png",
			"/assets/textures/Virus.png",
			"/assets/textures/WaterBullet.png",
			"/assets/textures/WaterWeapon.png",
			"/assets/textures/WorkBoss.jpg",
			"/assets/textures/city.png",
			"/assets/textures/crosshair.png",
		],
	},
];
